name: Build All Docker

on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

jobs:
  build-php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4,8.0 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: chmod +x jbdock.sh
      - name: Log into docker
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: sed 's/\(PHP_VERSION=\).*/\1${{ matrix.php }}/g' .env.example > .env
      - name: Build Image
        run: ./jbdock.sh d build php
      - name: Push image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker-compose push php
  build-other:
    runs-on: ubuntu-latest
    needs: build-php
    strategy:
      matrix:
        name: [ 'node', 'nginx', 'mysql', 'redis']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: chmod +x jbdock.sh
      - name: Log into docker
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: ./jbdock.sh d build ${{ matrix.name }}
      - name: Push image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker-compose push ${{ matrix.name }}
